### ISSUE TITLE
Hey，is that finish?

### ISSUE THREAD

**Issue by bakabird** [freehuntx/frida-mono#1]
Is the code in branch `feature/v1` work?
I'm exploring frida-mono-api now.

**Comment by freehuntx** [comment]
Alot of things happened in my life and interests shifted. So currently im not working on it.  
In the future i might work more on it but for now its freezed.

**Comment by SantiiRepair** [comment]
> Alot of things happened in my life and interests shifted. So currently im not working on it. In the future i might work more on it but for now its freezed.

Bro, are you ok?

**Comment by freehuntx** [comment]
Yes but shifted priorities as i also became a dad ☺️
Project is on hold.

**Comment by SantiiRepair** [comment]
Congratulations bro 🙌
